name: aloec_mobile
description: "ALOEC - Aplicación Móvil de Dieta de Jugos Verdes, Planes e IMC"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localización (i18n)
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Gestión de Estados e Inyección
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navegación y Rutas
  go_router: ^17.2.3

  # Firebase Backend
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  firebase_storage: ^13.4.1
  firebase_messaging: ^16.2.2
  firebase_analytics: ^12.4.1
  firebase_crashlytics: ^5.2.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.0

  # Multimedia y Componentes
  cached_video_player: ^2.0.4
  cached_network_image: ^3.3.1
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generación de código
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  # Configuración de assets e idiomas
  generate: true
  assets:
    - assets/images/
    - assets/videos/
