/**
 * ALOEC Firestore Seed Script — Authenticated
 * Run from aloec_admin/: node seed-data.mjs
 */
import { initializeApp } from 'firebase/app';
import { getFirestore, doc, setDoc } from 'firebase/firestore';
import { getAuth, signInWithEmailAndPassword } from 'firebase/auth';
import { createInterface } from 'readline';

const app = initializeApp({
  apiKey: "AIzaSyBSBkVK3-0t6kEN8IBE2saW2AuTQPzhGz4",
  authDomain: "app-aloec.firebaseapp.com",
  projectId: "app-aloec",
  storageBucket: "app-aloec.firebasestorage.app",
  messagingSenderId: "75165578833",
  appId: "1:75165578833:web:db63c434d7c68e848e6a70",
});
const db = getFirestore(app);
const auth = getAuth(app);

const recipes = [
  { id:'recipe_ensalada_frutas', title:'Ensalada de Frutas ALOEC', description:'Ensalada de frutas frescas de temporada, ideal para el desayuno. Rica en vitaminas, antioxidantes y fibra natural.', preparation:'Paso 1: Seleccionar frutas frescas de temporada (papaya, piña, fresas, banano, manzana).\nPaso 2: Lavar y cortar en cubos medianos.\nPaso 3: Mezclar en un bowl grande.\nPaso 4: Servir inmediatamente.', imageUrl:'', ingredients:['1 taza de papaya picada','1 taza de piña picada','1/2 taza de fresas','1 banano','1 manzana verde','Jugo de 1 limón (opcional)'], benefits:['Alta en vitaminas A, C y E','Rica en antioxidantes naturales','Aporta fibra dietética','Bajo en calorías','Ideal para la digestión matutina'], nutritionalValues:{calories:180,proteins:2,carbs:42,fats:0.5,fiber:6,vitamins:['Vitamina C','Vitamina A','Vitamina E','Ácido fólico'],minerals:['Potasio','Magnesio']}, prepTime:10, difficulty:'Fácil', category:'breakfast', tags:['desayuno','frutas','bajo en calorías','vitaminas'], isPremium:false, isActive:true, order:1 },
  { id:'recipe_jugo_zanahoria', title:'Jugo de Zanahoria Natural', description:'Jugo de zanahoria fresco, fundamental en los protocolos ALOEC. Rico en betacarotenos y vitamina A.', preparation:'Paso 1: Lavar bien 4-5 zanahorias grandes.\nPaso 2: Pasar por el extractor de jugos.\nPaso 3: Servir inmediatamente sin colar.\nPaso 4: Puede añadir jengibre fresco.', imageUrl:'', ingredients:['4-5 zanahorias grandes','Trozo pequeño de jengibre fresco (opcional)'], benefits:['Rico en betacarotenos','Fortalece el sistema inmunológico','Mejora la salud de la piel','Apoya la salud ocular','Desintoxicante natural del hígado'], nutritionalValues:{calories:95,proteins:2,carbs:22,fats:0.3,fiber:4,vitamins:['Vitamina A','Vitamina K','Vitamina C'],minerals:['Potasio','Hierro']}, prepTime:5, difficulty:'Fácil', category:'green_juice', tags:['jugo','zanahoria','detox','vitamina A','terapia gerson'], isPremium:false, isActive:true, order:2 },
  { id:'recipe_jugo_zanahoria_manzana', title:'Jugo de Zanahoria y Manzana Verde', description:'Combinación clásica de los protocolos ALOEC para la media tarde.', preparation:'Paso 1: Lavar 3-4 zanahorias y 1 manzana verde.\nPaso 2: Cortar en trozos para el extractor.\nPaso 3: Alternar zanahoria y manzana.\nPaso 4: Servir inmediatamente.', imageUrl:'', ingredients:['3-4 zanahorias grandes','1 manzana verde'], benefits:['Combinación ideal de betacarotenos y pectina','Regula niveles de azúcar','Fortalece el sistema digestivo','Apoya la desintoxicación del hígado'], nutritionalValues:{calories:130,proteins:2,carbs:30,fats:0.4,fiber:5,vitamins:['Vitamina A','Vitamina C','Vitamina K'],minerals:['Potasio','Hierro','Magnesio']}, prepTime:8, difficulty:'Fácil', category:'green_juice', tags:['jugo','zanahoria','manzana','detox','terapia gerson'], isPremium:false, isActive:true, order:3 },
  { id:'recipe_jugo_verde_renovador', title:'Jugo Verde Renovador ALOEC', description:'Jugo verde insignia de ALOEC. Espinacas, manzana verde, jengibre, piña y hierbabuena. Preparación en libro "Ama lo que comes" pág. 68.', preparation:'Paso 1: Lavar un puñado grande de espinacas frescas.\nPaso 2: Cortar 2 manzanas verdes, jengibre y piña.\nPaso 3: Añadir hojas de hierbabuena fresca.\nPaso 4: Pasar por el extractor de jugos.\nPaso 5: Servir inmediatamente.\n\nReceta completa: libro "Ama lo que comes" página 68.', imageUrl:'', ingredients:['1 puñado grande de espinacas frescas','2 manzanas verdes','1 trozo de jengibre fresco (2-3 cm)','2 rodajas de piña','Hojas de hierbabuena fresca'], benefits:['Potente desintoxicante','Rico en clorofila y hierro','Antiinflamatorio natural','Mejora la digestión','Energizante sin cafeína','Fortalece el sistema inmunológico'], nutritionalValues:{calories:110,proteins:3,carbs:24,fats:0.5,fiber:5,vitamins:['Vitamina A','Vitamina C','Vitamina K','Ácido fólico'],minerals:['Hierro','Magnesio','Potasio','Calcio']}, prepTime:10, difficulty:'Fácil', category:'green_juice', tags:['jugo verde','detox','espinaca','renovador','terapia gerson','insignia'], isPremium:true, isActive:true, order:4 },
  { id:'recipe_ensalada_colorida', title:'Ensalada Colorida con Vinagre de Sidra', description:'Ensalada variada con vinagre de sidra de manzana. Acompaña el almuerzo de los protocolos.', preparation:'Paso 1: Lavar y picar lechuga, tomate, pepino, zanahoria rallada, remolacha y pimiento.\nPaso 2: Mezclar en un plato grande.\nPaso 3: Aliñar con una cucharada de vinagre de sidra de manzana.\nPaso 4: Acompañar con pescado al vapor y papas.', imageUrl:'', ingredients:['Lechuga fresca','Tomate','Pepino','Zanahoria rallada','Remolacha rallada','Pimiento','1 cda vinagre de sidra de manzana'], benefits:['Alta en fibra','El vinagre de sidra mejora la digestión','Variedad de antioxidantes','Baja en calorías y saciante'], nutritionalValues:{calories:85,proteins:3,carbs:16,fats:1,fiber:5,vitamins:['Vitamina A','Vitamina C','Vitamina K','Vitamina E'],minerals:['Hierro','Potasio','Magnesio']}, prepTime:15, difficulty:'Fácil', category:'salad', tags:['ensalada','almuerzo','vinagre de sidra','colorida','fibra'], isPremium:false, isActive:true, order:5 },
  { id:'recipe_sopa_vegetales', title:'Sopa de Vegetales ALOEC', description:'Sopa de vegetales frescos para la cena. Ligera, nutritiva y fácil de digerir.', preparation:'Paso 1: Picar vegetales frescos (calabacín, zanahoria, apio, cebolla, tomate).\nPaso 2: Cocinar en agua a fuego medio por 20 minutos.\nPaso 3: Condimentar con hierbas frescas (sin sal refinada).\nPaso 4: Servir caliente.', imageUrl:'', ingredients:['1 calabacín','2 zanahorias','2 tallos de apio','1 cebolla','2 tomates','Hierbas frescas al gusto','Agua purificada'], benefits:['Fácil de digerir','Hidratante','Rica en minerales','Ideal para la cena','Baja en calorías'], nutritionalValues:{calories:75,proteins:3,carbs:14,fats:0.5,fiber:4,vitamins:['Vitamina A','Vitamina C'],minerals:['Potasio','Magnesio']}, prepTime:30, difficulty:'Fácil', category:'main_dish', tags:['sopa','cena','vegetales','ligera','digestión'], isPremium:false, isActive:true, order:6 },
  { id:'recipe_batido_quinua_dorada', title:'Batido de Leche de Quinua Dorada', description:'Batido nutritivo para el protocolo de recuperación de peso. Quinua con cúrcuma antiinflamatoria.', preparation:'Paso 1: Cocinar 1/2 taza de quinua lavada en 2 tazas de agua por 15 min.\nPaso 2: Licuar con 1 taza de leche vegetal.\nPaso 3: Añadir 1/2 cdita de cúrcuma, canela y miel.\nPaso 4: Licuar hasta consistencia cremosa.\nPaso 5: Servir tibio o frío.', imageUrl:'', ingredients:['1/2 taza de quinua','2 tazas de agua','1 taza de leche vegetal','1/2 cdita de cúrcuma','Canela al gusto','Miel de abeja al gusto'], benefits:['Proteína vegetal completa','Alto en calorías saludables','Cúrcuma antiinflamatoria','Rico en hierro y magnesio','Sin lactosa'], nutritionalValues:{calories:320,proteins:12,carbs:48,fats:8,fiber:5,vitamins:['Vitamina B1','Vitamina B2','Vitamina B6','Vitamina E'],minerals:['Hierro','Magnesio','Fósforo','Zinc','Manganeso']}, prepTime:20, difficulty:'Medio', category:'smoothie', tags:['batido','quinua','proteína','subir peso','desayuno','cúrcuma'], isPremium:true, isActive:true, order:7 },
  { id:'recipe_ensalada_papas_horno', title:'Ensalada con Papas al Horno', description:'Ensalada sustanciosa con papas al horno, vinagre de sidra y aceite de linaza. Para protocolos de IMC alto.', preparation:'Paso 1: Lavar y cortar papas en cubos, hornear a 180°C por 25 min.\nPaso 2: Preparar ensalada verde.\nPaso 3: Combinar papas tibias con ensalada.\nPaso 4: Aderezar con vinagre de sidra y aceite de linaza.', imageUrl:'', ingredients:['3 papas medianas','Lechuga fresca','Tomate','Pepino','Vinagre de sidra de manzana','1 cda de aceite de linaza'], benefits:['Saciante y nutritiva','Aceite de linaza aporta omega-3','Carbohidratos complejos','Vinagre de sidra mejora digestión'], nutritionalValues:{calories:280,proteins:6,carbs:45,fats:8,fiber:6,vitamins:['Vitamina C','Vitamina B6'],minerals:['Potasio','Hierro','Magnesio']}, prepTime:35, difficulty:'Medio', category:'main_dish', tags:['ensalada','papas','cena','aceite de linaza','omega-3'], isPremium:false, isActive:true, order:8 },
  { id:'recipe_pollo_vapor_ensalada', title:'Pollo al Vapor con Ensalada', description:'Pollo de campo al vapor con ensalada fresca. Cena del protocolo de recuperación de peso.', preparation:'Paso 1: Cocinar la pechuga al vapor por 20 min.\nPaso 2: Preparar ensalada fresca.\nPaso 3: Servir el pollo en láminas sobre la ensalada.\nPaso 4: Aderezar con limón y hierbas.', imageUrl:'', ingredients:['1 pechuga de pollo de campo','Lechuga fresca','Tomate','Pepino','Jugo de limón','Hierbas frescas'], benefits:['Alto en proteína','Bajo en grasa al vapor','Pollo de campo libre de hormonas','Fácil de digerir'], nutritionalValues:{calories:250,proteins:35,carbs:8,fats:6,fiber:3,vitamins:['Vitamina B3','Vitamina B6','Vitamina C'],minerals:['Fósforo','Selenio','Potasio']}, prepTime:25, difficulty:'Fácil', category:'main_dish', tags:['pollo','vapor','cena','proteína','bajo en grasa'], isPremium:false, isActive:true, order:9 },
  { id:'recipe_pescado_vapor', title:'Pescado al Vapor con Papas y Ensalada', description:'Plato principal de los protocolos ALOEC. Se puede variar con pollo de campo 2 veces por semana.', preparation:'Paso 1: Cocinar filete de pescado al vapor 15 min con hierbas.\nPaso 2: Cocinar papas en agua.\nPaso 3: Preparar ensalada colorida con vinagre de sidra.\nPaso 4: Servir con jugo de zanahoria.', imageUrl:'', ingredients:['1 filete de pescado fresco','Papas cocinadas','Ensalada colorida','Vinagre de sidra de manzana','Hierbas frescas','Jugo de zanahoria'], benefits:['Alto en omega-3','Proteína de alta calidad','Fácil de digerir al vapor','Completo en macronutrientes'], nutritionalValues:{calories:350,proteins:30,carbs:35,fats:8,fiber:5,vitamins:['Vitamina D','Vitamina B12','Vitamina C'],minerals:['Fósforo','Selenio','Yodo','Potasio']}, prepTime:30, difficulty:'Medio', category:'main_dish', tags:['pescado','vapor','almuerzo','omega-3','proteína'], isPremium:false, isActive:true, order:10 },
];

const protocols = [
  { id:'protocol_underweight', title:'Protocolo para Recuperar Peso', subtitle:'IMC menor a 18.5', description:'Diseñado para pacientes que deseen recuperar peso. Incluye batidos de quinua dorada, suplementos y alimentación alta en calorías saludables.', imageUrl:'', bmiCategory:'underweight', bmiMin:null, bmiMax:18.5, linkedCourseTag:'terapia_gerson', linkedCourses:[], isPremium:true, isActive:true, order:1,
    importantNotes:['Puede variar el pescado con pollo de campo libre de hormonas, 2 veces por semana.','Una vez que haya recuperado su peso ideal, puede asistir al gimnasio a fortalecer su masa muscular.','Contacto y preguntas: +593 99 950 4321'],
    schedule:[
      {mealType:'breakfast',time:'07:00 AM',label:'Desayuno',icon:'🌅',recipeId:'recipe_batido_quinua_dorada',recipeName:'Batido de Leche de Quinua Dorada',recipeImageUrl:'',notes:'',items:['Tomar una cápsula de hígado y pancreatina antes del desayuno','Batido de leche de quinua dorada']},
      {mealType:'morning_snack',time:'10:30 AM',label:'Media Mañana',icon:'💊',recipeId:'',recipeName:'',recipeImageUrl:'',notes:'',items:['Tomar vitamina B12']},
      {mealType:'lunch',time:'01:00 PM',label:'Almuerzo',icon:'🥗',recipeId:'recipe_pescado_vapor',recipeName:'Pescado al Vapor con Papas y Ensalada',recipeImageUrl:'',notes:'',items:['Tomar una cápsula de hígado y pancreatina antes del almuerzo','Ensalada colorida con vinagre de sidra de manzana','Pescado al vapor, papas cocinadas y jugo de zanahoria']},
      {mealType:'afternoon_snack',time:'03:00 PM',label:'Media Tarde',icon:'🥤',recipeId:'recipe_batido_quinua_dorada',recipeName:'Batido de Leche de Quinua Dorada',recipeImageUrl:'',notes:'',items:['Batido de leche de quinua dorada']},
      {mealType:'dinner',time:'06:00 PM',label:'Cena',icon:'🍗',recipeId:'recipe_pollo_vapor_ensalada',recipeName:'Pollo al Vapor con Ensalada',recipeImageUrl:'',notes:'Tomar cápsula de selenio a las 16h00',items:['Pollo al vapor más ensalada','Tomar una cápsula de hígado y pancreatina después de la cena']}
    ]},
  { id:'protocol_overweight', title:'Protocolo para Pérdida de Peso', subtitle:'IMC 25 hasta 29.5 (Sobrepeso)', description:'Diseñado para pacientes con IMC entre 25 y 29.5. Incluye jugos verdes, suplementos naturales y enema de café nocturno.', imageUrl:'', bmiCategory:'overweight', bmiMin:25, bmiMax:30, linkedCourseTag:'terapia_gerson', linkedCourses:[], isPremium:true, isActive:true, order:2,
    importantNotes:['Si es su primer enema de café, puede comenzar con 250 ml e ir aumentando progresivamente hasta llegar a un litro.','Si usted es diabético, reemplace el jugo verde renovador por el jugo verde de la terapia Gerson.','Puede variar el pescado con pollo de campo libre de hormonas, 2 veces por semana.','Contacto y preguntas: +593 99 950 4321'],
    schedule:[
      {mealType:'breakfast',time:'08:00 AM',label:'Desayuno',icon:'🍎',recipeId:'recipe_ensalada_frutas',recipeName:'Ensalada de Frutas ALOEC',recipeImageUrl:'',notes:'Caminar todos los días por media hora',items:['Tomar una cápsula de hígado y pancreatina antes del desayuno','Ensalada de frutas','Caminar todos los días por media hora']},
      {mealType:'morning_snack',time:'10:30 AM',label:'Media Mañana',icon:'🥕',recipeId:'recipe_jugo_verde_renovador',recipeName:'Jugo Verde Renovador ALOEC',recipeImageUrl:'',notes:'',items:['Jugo verde renovador','A las 11 AM tomar vitamina B12']},
      {mealType:'lunch',time:'01:00 PM',label:'Almuerzo',icon:'🥗',recipeId:'recipe_pescado_vapor',recipeName:'Pescado al Vapor con Papas y Ensalada',recipeImageUrl:'',notes:'',items:['Tomar una cápsula de hígado y pancreatina antes del almuerzo','Ensalada colorida con vinagre de sidra de manzana','Pescado al vapor, papas cocinadas y jugo de zanahoria']},
      {mealType:'afternoon_snack',time:'03:00 PM',label:'Media Tarde',icon:'🥤',recipeId:'recipe_jugo_zanahoria_manzana',recipeName:'Jugo de Zanahoria y Manzana Verde',recipeImageUrl:'',notes:'Tomar cápsula de selenio a las 16h00',items:['Jugo de zanahoria y manzana verde','Tomar una cápsula de hígado','16h00: tomar una cápsula de selenio']},
      {mealType:'dinner',time:'06:00 PM',label:'Cena',icon:'🍵',recipeId:'recipe_sopa_vegetales',recipeName:'Sopa de Vegetales ALOEC',recipeImageUrl:'',notes:'Enema de café a las 21h00',items:['Tomar una cápsula de hígado y pancreatina antes de la cena','Una sopa de vegetales a escoger','21h00 - Enema de café: libro "Ama lo que comes" pág. 72-75']}
    ]},
  { id:'protocol_obesity1', title:'Protocolo para Pérdida de Peso', subtitle:'IMC 30 hasta 34.5 (Obesidad I)', description:'Diseñado para pacientes con IMC entre 30 y 34.5. Incluye jugos terapéuticos, suplementos y enemas de café (mediodía y noche).', imageUrl:'', bmiCategory:'obesity1', bmiMin:30, bmiMax:35, linkedCourseTag:'terapia_gerson', linkedCourses:[], isPremium:true, isActive:true, order:3,
    importantNotes:['Si es su primer enema de café, puede comenzar con 250 ml e ir aumentando progresivamente hasta llegar a un litro.','Si usted es diabético, reemplace el jugo verde renovador por el jugo verde de la terapia Gerson.','Puede variar el pescado con pollo de campo libre de hormonas, 2 veces por semana.','Contacto y preguntas: +593 99 950 4321'],
    schedule:[
      {mealType:'breakfast',time:'08:00 AM',label:'Desayuno',icon:'🍎',recipeId:'recipe_ensalada_frutas',recipeName:'Ensalada de Frutas ALOEC',recipeImageUrl:'',notes:'Caminar todos los días por media hora',items:['Tomar una cápsula de hígado y pancreatina antes del desayuno','Ensalada de frutas y jugo de zanahoria','Caminar todos los días por media hora']},
      {mealType:'morning_snack',time:'10:00 AM',label:'Media Mañana',icon:'🥕',recipeId:'recipe_jugo_verde_renovador',recipeName:'Jugo Verde Renovador ALOEC',recipeImageUrl:'',notes:'',items:['Jugo verde renovador','A las 11 AM tomar vitamina B12']},
      {mealType:'lunch',time:'01:00 PM',label:'Almuerzo',icon:'🥗',recipeId:'recipe_pescado_vapor',recipeName:'Pescado al Vapor con Papas y Ensalada',recipeImageUrl:'',notes:'Enema de café a las 14h00',items:['Tomar una cápsula de hígado y pancreatina antes del almuerzo','Ensalada colorida con vinagre de sidra de manzana','Pescado al vapor, papas cocinadas y jugo de zanahoria','14h00 - Enema de café: libro "Ama lo que comes" pág. 72-75']},
      {mealType:'afternoon_snack',time:'03:00 PM',label:'Media Tarde',icon:'🥤',recipeId:'recipe_jugo_zanahoria_manzana',recipeName:'Jugo de Zanahoria y Manzana Verde',recipeImageUrl:'',notes:'Tomar cápsula de selenio a las 16h00',items:['Jugo de zanahoria y manzana verde','Tomar una cápsula de hígado','16h00: tomar una cápsula de selenio']},
      {mealType:'dinner',time:'06:00 PM',label:'Cena',icon:'🍵',recipeId:'recipe_sopa_vegetales',recipeName:'Sopa de Vegetales ALOEC',recipeImageUrl:'',notes:'Enema de café a las 21h00',items:['Tomar una cápsula de hígado y pancreatina antes de la cena','Una sopa de vegetales a escoger','21h00 - Enema de café: libro "Ama lo que comes" pág. 72-75']}
    ]},
  { id:'protocol_obesity3', title:'Protocolo para Pérdida de Peso', subtitle:'IMC 40 o Superior (Obesidad Severa)', description:'Diseñado para pacientes con IMC de 40+. Incluye enzimas digestivas, cardo mariano para el hígado y enemas de café. Requiere supervisión médica.', imageUrl:'', bmiCategory:'obesity3', bmiMin:40, bmiMax:null, linkedCourseTag:'terapia_gerson', linkedCourses:[], isPremium:true, isActive:true, order:5,
    importantNotes:['Si es su primer enema de café, puede comenzar con 250 ml e ir aumentando progresivamente.','Si es diabético, reemplace el jugo verde renovador por el jugo verde de la terapia Gerson.','Puede variar el pescado con pollo de campo libre de hormonas, 2 veces por semana.','Consultar con su médico antes de iniciar este protocolo.','Contacto y preguntas: +593 99 950 4321'],
    schedule:[
      {mealType:'breakfast',time:'08:00 AM',label:'Desayuno',icon:'🍎',recipeId:'recipe_ensalada_frutas',recipeName:'Ensalada de Frutas ALOEC',recipeImageUrl:'',notes:'Caminar todos los días por media hora',items:['Tomar una cápsula de hígado y pancreatina antes del desayuno','Tomar enzimas digestivas antes del desayuno','Ensalada de frutas y jugo de zanahoria','Caminar todos los días por media hora']},
      {mealType:'morning_snack',time:'10:00 AM',label:'Media Mañana',icon:'🥕',recipeId:'recipe_jugo_verde_renovador',recipeName:'Jugo Verde Renovador ALOEC',recipeImageUrl:'',notes:'',items:['Jugo verde renovador','A las 11 AM tomar vitamina B12','Tomar una cápsula de cardo mariano']},
      {mealType:'lunch',time:'01:00 PM',label:'Almuerzo',icon:'🥗',recipeId:'recipe_pescado_vapor',recipeName:'Pescado al Vapor con Papas y Ensalada',recipeImageUrl:'',notes:'Enema de café a las 14h00',items:['Tomar una cápsula de hígado y pancreatina antes del almuerzo','Ensalada colorida con vinagre de sidra de manzana','Pescado al vapor, papas cocinadas y jugo de zanahoria','14h00 - Enema de café: libro "Ama lo que comes" pág. 72-75']},
      {mealType:'afternoon_snack',time:'03:00 PM',label:'Media Tarde',icon:'🥤',recipeId:'recipe_jugo_zanahoria_manzana',recipeName:'Jugo de Zanahoria y Manzana Verde',recipeImageUrl:'',notes:'Tomar cápsula de selenio a las 16h00',items:['Jugo de zanahoria y manzana verde','Tomar una cápsula de hígado','16h00: tomar una cápsula de selenio']},
      {mealType:'dinner',time:'06:00 PM',label:'Cena',icon:'🍽️',recipeId:'recipe_ensalada_papas_horno',recipeName:'Ensalada con Papas al Horno',recipeImageUrl:'',notes:'Enema de café a las 21h00. Aderezo: vinagre de sidra y aceite de linaza.',items:['Tomar una cápsula de hígado y pancreatina antes de la cena','Ensalada y papas al horno','Aderezo: vinagre de sidra de manzana y aceite de linaza','21h00 - Enema de café: libro "Ama lo que comes" pág. 72-75']}
    ]},
];

function prompt(q) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(r => rl.question(q, a => { rl.close(); r(a); }));
}

async function seed() {
  console.log('\n🌱 ALOEC Firestore Seed\n━━━━━━━━━━━━━━━━━━━━━━');
  const email = await prompt('Email admin: ');
  const password = await prompt('Contraseña: ');
  console.log('\n🔐 Autenticando...');
  await signInWithEmailAndPassword(auth, email, password);
  console.log('✅ OK\n');

  console.log('📗 Subiendo 10 recetas...');
  for (const r of recipes) {
    const { id, ...d } = r;
    await setDoc(doc(db, 'recipes', id), { ...d, viewsCount: 0, createdAt: new Date(), updatedAt: new Date() });
    console.log(`  ✅ ${r.title}`);
  }

  console.log('\n📋 Subiendo 4 protocolos...');
  for (const p of protocols) {
    const { id, ...d } = p;
    await setDoc(doc(db, 'diet_protocols', id), { ...d, createdAt: new Date(), updatedAt: new Date() });
    console.log(`  ✅ ${p.title} (${p.bmiCategory})`);
  }

  console.log('\n⚙️  Subiendo app_config...');
  await setDoc(doc(db, 'app_config', 'main'), { primaryColor:'#2E7D32', accentColor:'#66BB6A', banners:[], welcomeMessage:'¡Bienvenido a ALOEC!', appVersion:{minimum:'1.0.0',latest:'1.0.0',updateUrl:''}, maintenanceMode:false, updatedAt:new Date() });
  console.log('  ✅ OK');

  console.log('\n🎉 ¡Seed completado! Abre el admin para verificar.\n');
  process.exit(0);
}

seed().catch(e => { console.error('❌', e.message); process.exit(1); });
